definitions:
  models.ErrorMsg:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  models.PlayStatus:
    enum:
    - Dealer Bust
    - Player Wins
    - Dealer Wins
    - Draw
    - Playing
    - Bust
    type: string
    x-enum-varnames:
    - DealerBust
    - PlayerWins
    - DealerWins
    - Draw
    - Playing
    - Bust
  models.ResponseMsg:
    properties:
      cards:
        items:
          type: string
        type: array
      dealerCards:
        items:
          type: string
        type: array
      dealerValue:
        type: integer
      device:
        type: string
      handValue:
        type: integer
      status:
        $ref: '#/definitions/models.PlayStatus'
    type: object
info:
  contact: {}
paths:
  /api/v1/deal:
    get:
      consumes:
      - application/json
      description: Start a new game or deal for an existing one.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorMsg'
      summary: start game
      tags:
      - Game
  /api/v1/hit:
    get:
      consumes:
      - application/json
      description: Draw a new card from the dealer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseMsg'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorMsg'
      summary: hit move
      tags:
      - Game
swagger: "2.0"
