definitions:
  models.ErrorMsg:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  models.PlayStatus:
    enum:
    - Dealer Bust
    - Player Wins
    - Dealer Wins
    - Draw
    - Playing
    - Bust
    type: string
    x-enum-varnames:
    - DealerBust
    - PlayerWins
    - DealerWins
    - Draw
    - Playing
    - Bust
  models.ResponseMsg:
    properties:
      cards:
        items:
          type: string
        type: array
      dealerCards:
        items:
          type: string
        type: array
      dealerValue:
        type: integer
      device:
        type: string
      handValue:
        type: integer
      status:
        $ref: '#/definitions/models.PlayStatus'
      token:
        type: string
    type: object
  models.StatusMsg:
    properties:
      draws:
        type: integer
      loses:
        type: integer
      wins:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/deal:
    get:
      consumes:
      - application/json
      description: Start a new game or deal for an existing one.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorMsg'
      summary: start game
      tags:
      - Game
  /api/v1/history:
    get:
      consumes:
      - application/json
      description: Get all the games you played
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.StatusMsg'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorMsg'
      summary: get all games played
      tags:
      - Game
  /api/v1/hit:
    get:
      consumes:
      - application/json
      description: Draw a new card from the dealer
      parameters:
      - description: token id for a game
        in: query
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseMsg'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorMsg'
      summary: hit move
      tags:
      - Game
  /api/v1/stats:
    get:
      consumes:
      - application/json
      description: Get player stats of wins, loses and draws
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ResponseMsg'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorMsg'
      summary: Get player stats of wins, loses and draws
      tags:
      - Game
  /api/v1/stay:
    get:
      consumes:
      - application/json
      description: Stop drawing cards and allow dealer to draw cards
      parameters:
      - description: token id for a game
        in: query
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseMsg'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorMsg'
      summary: Stop drawing cards and allow dealer to draw cards
      tags:
      - Game
swagger: "2.0"
